#!/bin/bash

#
# install donkey as donkeycar
#
LHOME=/home/lubuntu
DOWNLOADS=/home/lubuntu/Downloads
IMGSRC=$HOME/Projects/DIYRoboCar/Donkey/donkey_2.5.0t_pi3.zip
IMG=donkey_2.5.0t_pi3.zip
#IMGSRC=https://www.dropbox.com/s/vb9wlju4aqx7i5o/donkey_2.2.img.zip

if [ ! -f $IMG ] ; then
  #wget $IMGSRC
  cp $IMGSRC .
fi
sudo mv $IMG FileSystem/$DOWNLOADS
sudo cp bashrc-d3 FileSystem/$LHOME/.bashrc
sudo cp wpa_supplicant.conf FileSystem/$DOWNLOADS
sudo cp wlan0.conf FileSystem/$DOWNLOADS
sudo cp sixpair.c FileSystem/$DOWNLOADS

sudo tar -xf mozBackup.tgz -C FileSystem/$LHOME
sudo mkdir FileSystem/$LHOME/Desktop
sudo cp *.desktop FileSystem/$LHOME/Desktop
sudo cp HowToDonkeyCar.pdf FileSystem/$LHOME/Desktop
sudo cp do-autohotspot.tgz FileSystem/$LHOME/Downloads

sudo cp timezone FileSystem/etc/timezone

#cp FileSystem/usr/share/zoneinfo/America/Los_Angeles FileSystem/etc/localtime 
#timedatectl set-timezone "America/Los_Angeles"

sudo mkdir FileSystem/$LHOME/bin
sudo cp D3-Scripts/script-* FileSystem/$LHOME/bin
sudo cp doit-cpu* FileSystem/$LHOME/bin
sudo chmod +x FileSystem/$LHOME/bin/*

sudo mkdir FileSystem/$LHOME/Documents
sudo cp lubuntu-default-wallpaper2.png FileSystem/$LHOME/Documents/lubuntu-default-wallpaper.png
sudo cp tools.txt FileSystem/$LHOME/Documents/DonkeyCar-tools-notes.txt
sudo cp -a ContinuousTraining FileSystem/$LHOME/Downloads
sudo tar -xzf desktopConfig.tgz -C FileSystem/$LHOME
sudo cp -a dot_imageioFFMPEG FileSystem/$LHOME/.imageio

sudo cp NetworkManager.conf FileSystem/etc/NetworkManager

sudo unzip DonkeySimLinux.zip -d FileSystem/home/lubuntu/

# installing Eric IDE
# copy eric tgz to Downloads and extract
# install QT5
## source env, apt install python-qscintilla2, pip install PyQt5 qscintilla
## apt clean
## python ./install.py

sudo chown -R 999:999 FileSystem/home/lubuntu
sudo chown -R 999:999 FileSystem/home/lubuntu/donkeycar/.git/*

