#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  SRCDIR=$(dirname $0)
  source $SRCDIR/script-config
  echo "using saved Donkeycar hostname:$myHostNameLocal"
else
  myHostNameLocal=$1
fi
ping -c 1 $myHostNameLocal
if [ ! $? == 0 ] ; then
  echo $myHostNameLocal Not Found! 
  echo Please recheck the spelling or verify both devices are on the same wireless network. 
  echo "Usage: script-auto-drive [hostname.local]"
  exit
fi

echo 'PASSED - Parameter checks'

# trap ctrl-c and call ctrl_c()
#trap ctrl_c INT
#function ctrl_c() {
#    echo "** Trapped CTRL-C"
#    python led_steady_status.py 11 0
#}
#python led_steady_status.py 11 1

#
# for autonomous driving
ssh pi@$myHostNameLocal -t "source env/bin/activate; cd d2; python ./manage.py drive --model=./models/myPilot.json" 
