#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  echo The hostname parmeter DOES NOT exist
  echo "Usage: script-drive <hostname.local>"
  exit
else
  ping -c 1 $1
  if [ ! $? == 0 ] ; then
    echo $1 Not Found! 
    echo Please recheck the spelling or verify both devices are on the same wireless network. 
    exit
  fi
fi

ssh pi@$1 -t "source /home/pi/env/bin/activate; cd; cd d2; python ./manage.py drive" 
# 
# for PS3 Joystick use
#ssh pi@$1 -t "source /home/pi/env/bin/activate; python cd; cd d2; ./manage.py drive --js" 
#
# for autonomous driving
# python d2/manage.py drive --model=myPilot 
