#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  echo The hostname parmeter DOES NOT exist
  echo "Usage: script-bluetoothPS3-final <your-hostname.local>"
  exit
else
  ping -c 1 $1
  if [ ! $? == 0 ] ; then
    echo $1 Not Found! 
    echo Please recheck the spelling or verify both devices are on the same wireless network. 
    exit
  fi
fi

if [ "$2" == "" ] ; then
  echo The Second parameter DOES NOT exist
  echo Replacing d2 with upgraded d2
  echo Any previoud d2/data and d2/models will be moved to the new d2 
else
  DONKEYDIR=$2
fi
echo 'PASSED - Parameter check'

#
# TODO: add checks for customizations to Config.py and manage.py
#
# updating rPi Donkey software
echo "example:"
echo "bluetoothctl"
echo "  > plug in PS3 controller"
echo "  > agent on"
echo "  > trust ps3_device_mac_id"
echo "  > quit"
echo ""
ssh pi@$1 -t "source env/bin/activate; echo 'Plug your PS3 Controller into the rPi via USB cable'; bluetoothctl" 

exit 
