#!/bin/bash

DONKEYDIR=~/d2
cd $DONKEYDIR

if [ "$1" == "" ] ; then
  echo Training Tub parmeter DOES NOT exist.
  echo choose on of the following directories and try again.
  echo "Usage: script-train [tub file]"
  ls data
  exit
else
  #echo :$1: parm exits
  if [ -d ~/d2/data/$1 ] ; then
    echo found $1
  else
    echo Training Tub directory DOES NOT exist.
    echo choose on of the following directories and try again.
    echo Usage: script-train [tub file]
    ls data
    exit
  fi
fi

python ./manage.py train --tub=$DONKEYDIR/data/$1 --model=$DONKEYDIR/models/myPilot
