#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  SRCDIR=$(dirname $0)
  source $SRCDIR/script-config
  echo "using saved Donkeycar hostname:$myHostNameLocal"
else
  myHostNameLocal=$1
fi
ping -c 1 $myHostNameLocal
if [ ! $? == 0 ] ; then
  echo $myHostNameLocal Not Found! 
  echo Please recheck the spelling or verify both devices are on the same wireless network. 
  echo "Usage: script-bluetoothPS3-final [your-hostname.local]"
  exit
fi

echo 'PASSED - Parameter checks'

#
# TODO: add checks for customizations to Config.py and manage.py
#
# updating rPi Donkey software
echo "example:"
echo "bluetoothctl"
echo "  > plug in PS3 controller"
echo "  > agent on"
echo "  > trust ps3_device_mac_id"
echo "  > quit"
echo ""
ssh pi@$myHostNameLocal -t "echo 'Plug your PS3 Controller into the rPi via USB cable'; bluetoothctl ; ls /dev/input/" 

exit 
