#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  SRCDIR=$(dirname $0)
  source $SRCDIR/script-config
  echo "using saved Donkeycar hostname:$myHostNameLocal"
else
  myHostNameLocal=$1
fi
ping -c 1 $myHostNameLocal
if [ ! $? == 0 ] ; then
  echo $myHostNameLocal Not Found! 
  echo Please recheck the spelling or verify both devices are on the same wireless network. 
  echo "Usage: script-rsync-pilot [hostname.local]"
  exit
fi

echo 'PASSED - Parameter checks'


if [ ! -d $HOME/$DONKEYDIR ] ; then
  echo The local directory, $HOME/$DONKEYDIR does NOT exist!
  echo script-createcar should be run before attempting to copy rPi pilot here.
  exit
fi


rsync -ah --progress $HOME/$DONKEYDIR/models pi@$myHostNameLocal:$DONKEYDIR
