#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  SRCDIR=$(dirname $0)
  source $SRCDIR/script-config
  echo "using saved Donkeycar hostname:$myHostNameLocal"
else
  myHostNameLocal=$1
fi
ping -c 1 $myHostNameLocal
if [ ! $? == 0 ] ; then
  echo $myHostNameLocal Not Found! 
  echo Please recheck the spelling or verify both devices are on the same wireless network. 
  echo "Usage: script-rpi-donkeyUpgrade [hostname.local]"
  exit
fi

echo 'PASSED - Parameter checks'

#
# TODO: add checks for customizations to Config.py and manage.py
#
# updating rPi Donkey software
ssh pi@$myHostNameLocal -t "source /usr/local/bin/virtualenvwrapper.sh;workon dk; cd donkeycar && git pull && pip install -e . && cd ; if [ -d ${DONKEYDIR}ORG ]; then rm -rf ${DONKEYDIR}ORG; fi; mv ${DONKEYDIR} ${DONKEYDIR}ORG ; donkey createcar --path=${DONKEYDIR} && mv ${DONKEYDIR}ORG/models/* ${DONKEYDIR}/models && mv ${DONKEYDIR}ORG/data/* ${DONKEYDIR}/data" 

