#!/bin/bash

DONKEYDIR=d2

if [ "$1" == "" ] ; then
  echo The hostname parmeter DOES NOT exist
  echo "Usage: script-drive <hostname.local>"
  exit
else
  ping -c 1 $1
  if [ ! $? == 0 ] ; then
    echo $1 Not Found! 
    echo Please recheck the spelling or verify both devices are on the same wireless network. 
    exit
  fi
fi

#
# for autonomous driving
ssh pi@$1 -t "source env/bin/activate; cd; cd d2; python ./manage.py drive --model=./models/myPilot" 
#
# using PS3 Joystick
#ssh pi@$1 -t "source env/bin/activate; cd; cd d2; python ./manage.py drive --model=./models/myPilot --js" 
